export const Env: Record<string, string> = {
    OPENAI_API_KEY: 'OPENAI_API_KEY',
    OPENAI_API_URL: 'OPENAI_API_URL',
    AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
    AWS_REGION: 'AWS_REGION'
}
